// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLST.data;

#nullable disable

namespace QLST.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20241129085128_Category")]
    partial class Category
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLST.data.Category", b =>
                {
                    b.Property<int>("idCat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCat"));

                    b.Property<string>("nameCat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCat");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("QLST.data.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CategoryidCat")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idCat")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nameCat")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("salePrice")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CategoryidCat");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("QLST.data.Product", b =>
                {
                    b.HasOne("QLST.data.Category", null)
                        .WithMany("ProductVN")
                        .HasForeignKey("CategoryidCat");
                });

            modelBuilder.Entity("QLST.data.Category", b =>
                {
                    b.Navigation("ProductVN");
                });
#pragma warning restore 612, 618
        }
    }
}
